Improved Build and Installation Scripts

diff --git a/airootfs/root/install b/airootfs/root/install
--- a/airootfs/root/install
+++ b/airootfs/root/install
@@ -1,9 +1,4 @@
 #!/bin/bash
-__appname__="cerebrow"
-__version__="v.0.5"
-__author__="@modaphukka"
-__date__="May 2016"
-__license__="Unlicensed"
 
 ##################
 ## GLOBAL STYLE ##
@@ -11,28 +6,7 @@ __license__="Unlicensed"
 red="\e[1;31m"
 green="\e[1;32m"
 yellow="\e[1;33m"
-blue="\e[1;34m"
-pink="\e[1;35m"
-cyan="\e[1;36m"
 nc="\e[0m"
-
-_banner() {
-    echo -e "\n" >&2
-    echo -e "$red        ...ArchLinux install...   $nc" >&2
-    echo -e "$red      ___________________________ $nc" >&2
-}
-
-_prompt() {
-   echo -e "\n$yellow==> $green$1 $red$2$nc" >&2
-   echo -e "$yellow==> ------------------------------------ $nc" >&2
-   echo -ne "$yellow==> $nc" >&2
-}
-
-_warning() {
-    echo -e "\n$green==> $red$1 $cyan[ENTER]$nc" >&2
-    echo -ne "$green==> $nc" >&2
-    read -s WARNING
-}
 
 ########################
 ## FiRMWARE DETECTiON ##
@@ -43,16 +17,18 @@ _firmware() {
         FIRMWARE="UEFI"
         part_table="GPT"
         part_code="g"
-        part_type=""
+        part_primary=""
+        part_extended=""
         boot_filesystem="fat -F 32"
     else
         FIRMWARE="BIOS"
         part_table="MBR"
         part_code="o"
-        part_type="p\n"
+        part_primary="p\n"
+        part_extended="e\n"
         boot_filesystem="ext2"
     fi
-    part_order=(0 1 2 3 4)
+    part_order=(0 1 2 3 4 5 6)
 }
 
 ######################
@@ -61,7 +37,7 @@ _firmware() {
 _settings() {
 
     # HOSTNAME
-    HOST_name=cerebrow.intranet
+    HOST_name=app.domain
 
     # ROOT PASSWORD
     ROOT_passwd=root
@@ -74,90 +50,77 @@ _disk_part() {
     part_error="$red \n==> Partitionning error! Exiting... $nc"
 
     # MBR or GPT
-    echo && _warning "$FIRMWARE detected! Listing disk..."
-    #until [[ ${_disk} =~ ^(sd|hd)[a-z]{1}$ ]]; do
-    #echo && fdisk -l
-    #_prompt "Enter disk to use (ex: sda):"
-    #read _disk
-    #done
-    _disk="sda"
+    echo -e "$FIRMWARE detected! Checking disk type..."
+
+    # HDA or SDA
+    fdisk -l | grep -q "/dev/sda"
+    if [[ $? -eq 0 ]]; then
+        _disk="sda"
+    else
+        _disk="hda"
+    fi
+    echo -e "/dev/$_disk detected! The drive will be erased..."
+
     fdisk -l /dev/$_disk
-    echo -e "$red \n  WARNiNG: This will erase the entire drive! $nc"
-    #_warning "Creating $part_table partition table on /dev/$_disk..."
+    echo -e "Creating $part_table partition table on /dev/$_disk..."
     printf "$part_code\nw" | fdisk /dev/$_disk
 
-    # BOOT on /dev/xxx1
-    #until [[ ${boot_size} =~ ^[0-9]{1,3}(M|G){1} \
-    #|| ${boot_size,,} == "y" ]]; do
-    echo -e "\n$cyan==> Partition size {M,G} => default: 512M $nc"
-    #_prompt "Boot partition size => default: $red[y]"
-    #read boot_size
-    #done
+    # TODO: Réaliser un calcul selon la taille du disque et la RAM 
+    # GENERIC VM --- HDD <= 10 GB; RAM <= 2 GB
     boot_size="512M"
-    #if [[ ${boot_size,,} == "y" ]]; then boot_size="512M"; fi
-    #_warning "Creating boot /dev/$_disk${part_order[1]} [$boot_size]..."
-    printf "n\n$part_type\n\n+$boot_size\nw" | fdisk /dev/$_disk
+    swap_size="2G"
+    root_size="1G"
+    var_size="2G"
+    data_size=""
+
+    # TODO: Vérifier si le filesystem ext4 correspond à l'utilisation des partitions / Voir ZFS
+    # https://wiki.archlinux.org/index.php/file_systems
+    # https://wiki.archlinux.org/index.php/Installing_Arch_Linux_on_ZFS
+
+    # BOOT on /dev/xxx1
+    echo -e "\n==> /boot partition size => default: 512M "
+    echo -e "Creating boot /dev/$_disk${part_order[1]} [$boot_size]..."
+    printf "n\n$part_primary\n\n+$boot_size\nw" | fdisk /dev/$_disk
     yes | mkfs.$boot_filesystem /dev/$_disk${part_order[1]}
 
     # SWAP on /dev/xxx2
-    #until [[ ${swap_size} =~ ^[0-9]{1,3}(M|G){1} \
-    #|| ${swap_size,,} == "y" ]]; do
-    echo -e "\n$cyan==> Partition size {M,G} => default: 2G $nc"
-    #_prompt "Swap partition size => default: $red[y]"
-    #read swap_size
-    #done
-    swap_size="2G"
-    #if [[ ${swap_size,,} == "y" ]]; then swap_size="2G"; fi
-    #_warning "Creating Swap /dev/$_disk${part_order[2]} [$swap_size]..."
-    printf "n\n$part_type\n\n+$swap_size\nw" | fdisk /dev/$_disk
+    echo -e "\n==> swap partition size => default: 2G "
+    echo -e "Creating swap /dev/$_disk${part_order[2]} [$swap_size]..."
+    printf "n\n$part_primary\n\n+$swap_size\nw" | fdisk /dev/$_disk
     yes | mkswap /dev/$_disk${part_order[2]}
 
-    # SYSTEM on /dev/xxx3
-    #until [[ ${sys_size} =~ ^[0-9]{1,3}(G|T|P){1} \
-    #|| ${sys_size,,} == "y" ]]; do
-    echo -e "\n$cyan==> Partition size {G,T,P} => default: 3G $nc"
-    #_prompt "System partition size => default: $red[y]"
-    #read sys_size
-    #done
-    sys_size="3G"
-    #if [[ ${sys_size,,} == "y" ]]; then sys_size="3G"; fi
-    #_warning "Creating System /dev/$_disk${part_order[3]} [$sys_size]..."
-    printf "n\n$part_type\n\n+$sys_size\nw" | fdisk /dev/$_disk
+    # ROOT on /dev/xxx3
+    echo -e "\n==> root partition size => default: 1G "
+    echo -e "Creating root /dev/$_disk${part_order[3]} [$root_size]..."
+    printf "n\n$part_primary\n\n+$root_size\nw" | fdisk /dev/$_disk
     yes | mkfs.ext4 /dev/$_disk${part_order[3]}
 
-    # HOME on /dev/xxx4
-    if [[ "$FIRMWARE" == "UEFI" ]]; then
-    #    until [[ ${home_size} =~ ^[0-9]{1,3}(G|T|P){1} \
-    #    || ${home_size,,} == "y" ]]; do
-        echo -e "\n$cyan==> Partition size {G,T,P} => default: free space $nc"
-    #    _prompt "Home partition size => default: $red[y]"
-    #    read home_size
-    #    done
-        home_size="y"
-        if [[ ${home_size,,} == "y" ]]; then
-            home_size=""
-            part_size="free space"
-    #    else
-    #        home_size="+$home_size"
-    #        part_size="$home_size"
-        fi
-    #    _warning "Creating Home /dev/$_disk${part_order[4]} [$part_size]..."
-    #    printf "n\n\n\n$home_size\nw" | fdisk /dev/$_disk
-    else
-        echo -e "\n$cyan==> Home partition will use all free space $nc"
-    #    _warning "Creating Home partition /dev/$_disk${part_order[4]}..."
-        printf "n\n$part_type\n\nw" | fdisk /dev/$_disk
-    fi
-    yes | mkfs.ext4 /dev/$_disk${part_order[4]}
+    # EXTENDED PARTITION /dev/xxx4
+    echo -e "Creating extended partition on /dev/$_disk${part_order[4]} ..."
+    printf "n\n$part_extended\n\n\nw" | fdisk /dev/$_disk
+
+    # VAR on /dev/xxx5
+    echo -e "\n==> /var partition size => default: 2G "
+    echo -e "Creating var /dev/$_disk${part_order[5]} [$var_size]..."
+    printf "n\n\n+$var_size\nw" | fdisk /dev/$_disk
+    yes | mkfs.ext4 /dev/$_disk${part_order[5]}
+
+    # TMP TODO: Already created by systemd as a tmpfs, check how to configure it.
+
+    # DATA on /dev/xxx6
+    echo -e "\n==> /data partition will use all free space "
+    echo -e "Creating /data /dev/$_disk${part_order[6]}..."
+    printf "n\n\n$data_size\nw" | fdisk /dev/$_disk
+    yes | mkfs.ext4 /dev/$_disk${part_order[6]}
 }
 
 ########################
 ## MOUNTiNG PARTiTiON ##
 ########################
 _mount_part() {
-    #_warning "Mounting partitions & activate swap..."
+    echo -e "Mounting partitions & activate swap..."
     mount /dev/$_disk${part_order[3]} /mnt
-    mkdir /mnt/{boot,home}
+    mkdir /mnt/{boot,var,tmp,data}
     if [[ "$FIRMWARE" == "UEFI" ]]; then
         mkdir -p /mnt/boot/efi/EFI
         mount -t vfat /dev/$_disk${part_order[1} /boot/efi
@@ -165,70 +128,76 @@ _mount_part() {
         mount /dev/$_disk${part_order[1]} /mnt/boot
     fi
     swapon /dev/$_disk${part_order[2]}
-    mount /dev/$_disk${part_order[4]} /mnt/home
+    mount /dev/$_disk${part_order[5]} /mnt/var
+    mount /dev/$_disk${part_order[6]} /mnt/data
 }
 
-#########################
-## iNSTALL BASE SYSTEM ##
-#########################
-_install_arch() {
-    echo -e "\n$cyan==> Installing base system... $nc" && sleep 2s
+####################
+## SYSTEM iNSTALL ##
+####################
+_install_system() {
+    echo -e "\n==> Installing system... "
+
     # Export root
+    echo -e "\n==> Exporting root partition... "
     time cp -ax / /mnt
 
     # Export kernel
+    echo -e "\n==> Exporting kernel... "
     cp -vaT /run/archiso/bootmnt/arch/boot/$(uname -m)/vmlinuz /mnt/boot/vmlinuz-linux
 
     # Generate fstab
+    echo -e "\n==> Generating fstab... "
     genfstab -U -p /mnt >> /mnt/etc/fstab
 
     # Chroot into
+    echo -e "\n==> Chroot & Configuration script injection... "
     arch-chroot /mnt /bin/bash <<EOF
-
-    # Disable dhcpd
-    rm /etc/udev/rules.d/81-dhcpcd.rules
 
     # Disable archiso services
     systemctl disable pacman-init.service choose-mirror.service
     rm -r /etc/systemd/system/{choose-mirror.service,pacman-init.service,etc-pacman.d-gnupg.mount,getty@tty1.service.d}
     rm /etc/systemd/scripts/choose-mirror
+    # TODO: Après que la partie configuration réseau soit finie, décommenter la ligne en dessous
+    #rm /etc/udev/rules.d/81-dhcpcd.rules
 
     # Remove archiso live scripts
     rm /root/{install,.zlogin}
     rm /etc/mkinitcpio-archiso.conf
     rm -r /etc/initcpio
 
+    # New .zlogin
+    echo '~/.configure' > /root/.zlogin
+    echo '~/.configure' > /etc/skel/.zlogin
+
     # Basic Configuration
-    echo -e "$cyan==> Setting root password... $nc" && sleep 2s
+    echo -e "==> Setting root password... "
     echo "root:${ROOT_passwd}" | chpasswd
-    echo -e "$cyan==> Setting hostname... $nc" && sleep 2s
+    echo -e "==> Setting hostname... "
     echo $HOST_name > /etc/hostname
-    echo -e "$cyan==> Setting and generating locale... $nc" && sleep 2s
-    echo "fr_FR.UTF-8 UTF-8" >> /etc/locale.gen && locale-gen
-    export LANG=fr_FR.UTF-8
-    echo "LANG=fr_FR.UTF-8" > /etc/locale.conf
-    echo -e "$cyan==> Setting keyboard... $nc" && sleep 2s
-    echo "KEYMAP=fr-pc" > /etc/vconsole.conf
-    echo -e "$cyan==> Setting timezone... $nc" && sleep 2s
-    ln -s /usr/share/zoneinfo/Europe/Paris /etc/localtime
+    echo -e "==> Setting and generating locale... "
+    locale-gen
+    echo -e "==> Setting keyboard... "
+    echo "KEYMAP=" > /etc/vconsole.conf
+    echo -e "==> Setting timezone... "
+    ln -s /usr/share/zoneinfo/UTC /etc/localtime
 
     # initramfs
-    echo -e "$cyan==> Setting Linux environment... $nc" && sleep 2s
+    echo -e "==> Setting Linux environment... "
     mkinitcpio -p linux
 
-    # Network Configuration
-    echo -e "$cyan==> Installing network... $nc" && sleep 2s
 EOF
 }
 
 ########################
-## iNSTALL BOOTLOADER ##
+## BOOTLOADER iNSTALL ##
 ########################
-_bootloader() {
-    _warning "Base system ok! Creating $FIRMWARE Boot Loader?"
+_install_bootloader() {
+    echo -e "Installating $FIRMWARE Boot Loader..."
     if [[ "$FIRMWARE" == "UEFI" ]]; then
         arch-chroot /mnt /bin/bash <<EOF
-        syslinux-install_update -iam
+        # TODO: Le cas doit être géré !
+        # https://wiki.archlinux.fr/Syslinux#Syst.C3.A8mes_UEFI
 EOF
     else
         arch-chroot /mnt /bin/bash <<EOF
@@ -237,25 +206,45 @@ EOF
     fi
 }
 
-###########################
-## RUN ARCHLiNUX iNSTALL ##
-###########################
-timedatectl set-timezone Europe/Paris
+########################
+## POSTGRESQL iNSTALL ##
+########################
+_install_postgresql() {
+    # TODO: Réaliser la création de la database
+    echo -e "SQL DUMP RESTORE..." && sleep 2s
+}
+
+########################
+## NODEJS APP iNSTALL ##
+########################
+_install_app() {
+    # TODO: Réaliser l'extraction des modules nodejs et autre ...
+    echo -e "NODEJS APP EXTRACTION..." && sleep 2s
+}
+
+######################
+## RUN iNSTALLATION ##
+######################
+
+# TODO: Réaliser un script dialog qui retranscrit les étapes ci-dessous
+
+timedatectl set-timezone UTC
 datetime=`date '+%d-%m-%Y_%Hh%Mm%Ss'`
-LOGFILE="install_arch_$datetime.log"
-_banner
+LOGFILE="install_$datetime.log"
+
 _firmware
 _settings
 _disk_part
 _mount_part
+
 if [ $? -eq 0 ]; then
-    echo && _warning "System ready! Do you wish to install ArchLinux?"
-    (_install_arch && _bootloader) 2>&1 | tee -a $LOGFILE
-    cp $LOGFILE /mnt/var/log/
-    echo -e "$green==>$red ArchLinux installation report: $nc"
-    cat $LOGFILE | grep "erreur" >/dev/null 2>&1
+    echo "System is ready for installation"
+    (_install_system && _install_bootloader && _install_postgresql && _install_app) 2>&1 | tee -a $LOGFILE
+    mv $LOGFILE /mnt/var/log/
+    echo -e "$green==>$red App installation report: $nc"
+    cat $LOGFILE | grep "error" >/dev/null 2>&1
     if [[ $? -eq 0 ]]; then
-        cat $LOGFILE | grep "erreur"
+        cat $LOGFILE | grep "error"
     else
         echo "Installation finished. No error reported."
     fi
@@ -263,5 +252,6 @@ else
     echo -e $part_error
     exit
 fi
-_warning "Done! $__appname__ $__version__ by $__author__ - $__license__"
+
+echo -e "Unmounting partition and Rebooting ..."
 umount -R /mnt && reboot
